site_name: Мій технічний блог

theme:
  name: material
  palette:
    scheme: slate # Темна тема (зручно для читання коду)
    primary: indigo

nav:
  - Головна: index.md
  - WordPress у Docker: second_pages.md
  - гайд по встановленню mkdocs : setup_guide.md